#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

env > .env

touch /var/www/html/storage/config/database.sqlite

if [ -z "$APP_KEY" ]; then
    echo "APP_KEY=" >> .env
    php /var/www/html/artisan key:generate --force
fi

php /var/www/html/artisan config:cache
php /var/www/html/artisan route:cache
php /var/www/html/artisan migrate --force

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
