#!/bin/sh

php -v

if [ ! -z "$UID" ]; then
    usermod -u $UID nobody
fi

if [ ! -z "$GID" ]; then
    groupmod -g $GID nobody
fi

if [ -z "$APP_KEY" ]; then
    export APP_KEY=`php artisan key:generate --show`
fi

env > .env

touch storage/config/database.sqlite
chown nobody:nobody storage/config/database.sqlite
php artisan migrate --force

/usr/bin/supervisord -c /etc/supervisor.conf
